name: "Error Annotator"
description: "Parses Unity Editor log files and outputs errors and warnings."
inputs:
  log-path:
    description: "Path to the Unity log file."
    required: true
    type: string
outputs:
  errors:
    description: "Parsed errors from the log file."
runs:
  using: "node16"
  main: "parse_logs.js"
with:
  log-path: ${{ inputs.log-path }}