name: "Error Annotator"
description: "Parse Unity logs for errors and warnings"

inputs:
  log-path:
    description: "Path to the log file"
    required: true
    default: ""

runs:
  using: "node12"
  main: "parse_logs.js"

env:
  INPUT_LOG_PATH: ${{ inputs.log-path }}
