name: Parse Unity Logs
on:
  workflow_dispatch:
    inputs:
      log-path:
        description: "Path to the log file"
        required: true
        type: choice
        options:
          - "logs/sample-project-failure.log"
          - "logs/sample-project-success.log"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  parse-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Fix node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Versions
        run: |
          echo "Printing versions:"
          echo "node version:"
          node --version
          echo "npm version:"
          npm --version
          lsb_release -a

      - name: Set up dependencies
        run: sudo npm install @actions/core

      - name: Print Working Directory
        run: pwd

      - name: Determine Log Path
        id: log_path
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Using log-path from manual input: ${{ inputs.log-path }}"
            echo "log-path=${{ inputs.log-path }}" >> $GITHUB_ENV
          else
            echo "Determining default log path for push/pull_request..."
            DEFAULT_LOG="logs/sample-project-failure.log"
            if [[ -z "$DEFAULT_LOG" ]]; then
              echo "::error::No log files found in build directory."
              exit 1
            fi
            echo "Default log detected: $DEFAULT_LOG"
            echo "log-path=$DEFAULT_LOG" >> $GITHUB_ENV
          fi

      - name: Print Log Path
        run: echo "log-path input -- ${{ env.log-path }}"

      - name: Parse Unity Logs
        id: logStep
        uses: ./.github/actions/error-annotator
        with:
          log-path: ${{ env.log-path }}

      - name: Print time output
        run: echo ${{ steps.logStep.outputs.time }}

      - name: Print Errors output
        run: |
          node ./.github/workflows/scripts/printErrors.js
        env:
          ERRORS: ${{ steps.logStep.outputs.errors }}
        
