name: Parse Unity Logs
on:
  workflow_dispatch:
    inputs:
      log-path:
        description: "Path to the log file"
        required: true
        type: choice
        options:
          - "logs/sample-project-failure.log"
          - "logs/sample-project-success.log"

jobs:
  parse-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Show Git Info
        run: git log -1 --oneline
        
      - name: List Files
        run: ls -la -R .github
      
      - name: Debug Working Directory
        run: pwd

      - name: List Repository Root
        run: ls -la -R .

      - name: List Action Directory
        run: ls -la -R ./github/actions/error-annotator  
      
      - name: Parse Unity Logs
        uses: ./github/actions/error-annotator
        with:
          log-path: ${{ inputs.log-path }}

